### ISSUE TITLE
Requests tab - Add New Boring Depth and Offset not saved

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#11]
Depth and Offset should be numbers, but front end does not prevent user from filling strings. Once the user inputs are strings, these two fields are default to 0.

**Comment by TU-MinW** [comment]
Add restrict to those numbers input

**Comment by GraceAi** [comment]
Can you apply the restrict to Ground Elevation, Depth of Bottom when boring type is SWM?

**Comment by TU-MinW** [comment]
Added

**Comment by GraceAi** [comment]
Ground Elevation and Depth of bottom still accept string input:

![image](https://cloud.githubusercontent.com/assets/11429203/13958976/86a20b58-f028-11e5-90da-f6299a7f7e28.png)

**Comment by GraceAi** [comment]
tested and confirmed ok
