### ISSUE TITLE
Requests tab - Delete Boring geometry issue

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#12]
After deleting a boring, the geometry is still on the map

**Comment by TU-MinW** [comment]
fixed issue. geometry is updated.

**Comment by GraceAi** [comment]
Tested and confirmed OK

**Comment by GraceAi** [comment]
Found another issue: even if Delete Boring fails, the geometry is still cleared.

**Comment by TU-MinW** [comment]
Updated

**Comment by GraceAi** [comment]
still encountered this issue

**Comment by GraceAi** [comment]
tested and confirmed ok
