### ISSUE TITLE
Requests tab - Edit Boring - error when trying to click on the map 

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#13]
Got the following error when trying to click a point on the map in order to change the x, y coordinates:
![image](https://cloud.githubusercontent.com/assets/11429203/13858500/57517dce-ec55-11e5-9b47-a8f81f3ae8b6.png)

**Comment by TU-MinW** [comment]
Issue fixed. Please try again.

**Comment by GraceAi** [comment]
Still encountered this issue. Steps to recreate:
1. open Edit Boring window to edit one boring, edit x, y coordinates or click on the map and cancel the changes.
2. open the Edit Boring window again, edit x, y coordinates or click on the map.

**Comment by TU-MinW** [comment]
Fixed again.

**Comment by GraceAi** [comment]
still encountered this issue...

**Comment by GraceAi** [comment]
tested and confirmed ok
