### ISSUE TITLE
Requests tab - Add New Boring - Geometry issue

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#14]
After adding three borings, the last boring's geometry is not displayed:

![image](https://cloud.githubusercontent.com/assets/11429203/13861383/68cb4374-ec63-11e5-9f0c-98071f4fd15e.png)

**Comment by GraceAi** [comment]
It seems to be caused by issue #7 multiple Add Boring Windows. Once I cancel one window, the highlighted geometry will be cleared. Since #7 is fixed, I will update the code and retest this issue.

**Comment by GraceAi** [comment]
This issue persists after I update the project. Steps to replicate it:
1. create a boring
2. click the boring to highlight the point.
3. click Add button to add a boring
4. close Add Boring Window before populate x, y coordinates
5. the current highlighted point will be cleared, which belongs to the boring added in step 1.

**Comment by TU-MinW** [comment]
Fixed issues. Please try again.

**Comment by GraceAi** [comment]
Tested and confirmed OK
