### ISSUE TITLE
Welcome window text error

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#2]
![image](https://cloud.githubusercontent.com/assets/11429203/13819937/a970ca18-eb71-11e5-9743-61eff9eb7df9.png)
Should be Boring Request Editor Version

**Comment by TU-MinW** [comment]
Fixed
![capture](https://cloud.githubusercontent.com/assets/13125065/13830552/de5edd64-eba3-11e5-8f79-fc03ffacd85b.GIF)
