### ISSUE TITLE
Reviews tab - Filter review does not return correct result

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#20]
The following criteria returns 0 result (should return the second one in datagrid).

![image](https://cloud.githubusercontent.com/assets/11429203/13888657/ea5f52b2-ed18-11e5-92a8-13e1b6870b96.png)

**Comment by TU-MinW** [comment]
Should work now

**Comment by GraceAi** [comment]
still see this issue

**Comment by GraceAi** [comment]
Encountered this issue when filtering with archived, approved requests. Steps to recreate:
1. click show archived, approved requests checkbox to display all requests.
2. filter reviews by selecting an accepted request's contract number.

In the following screenshot, service should return one request, but returns nothing:

![image](https://cloud.githubusercontent.com/assets/11429203/13987957/4bdb4742-f0e0-11e5-8b9f-0bdc08d9d5c3.png)

**Comment by TU-MinW** [comment]
Fixed in my local, haven't committed yet.

**Comment by GraceAi** [comment]
tested and confirmed ok
