### ISSUE TITLE
Reviews tab - request info and geometry should be cleared after filtering reviews

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#21]
After user applies the filters and datagrid is updated, the request information and geometry on the map should be cleared.

**Comment by TU-MinW** [comment]
Fixed

**Comment by GraceAi** [comment]
Geometry was cleared, but request information was not.

**Comment by TU-MinW** [comment]
Cleared request info after filter request

**Comment by GraceAi** [comment]
Tested and  confirmed ok
