### ISSUE TITLE
Borings tab - export error

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#26]
Encountered a web service issue when exporting borings:

![image](https://cloud.githubusercontent.com/assets/11429203/13932547/e38922d4-ef7e-11e5-817f-c07ca108cc5d.png)

**Comment by andywu123** [comment]
Should be Ok now, please feel free to test.

**Comment by GraceAi** [comment]
This error is gone. But I am encountering a file io error which is caused by virtual directory alias. 

![image](https://cloud.githubusercontent.com/assets/11429203/13987276/31a5b568-f0dd-11e5-939a-31de3df5b831.png)

Min, can you handle the alias of these two folders on server: C:\inetpub\wwwroot\DocumentManagement and C:\inetpub\wwwroot\DocumentManagement_Excel?

**Comment by GraceAi** [comment]
tested and confirmed ok
