### ISSUE TITLE
Borings tab - add new boring IO error

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#28]
Encountered a web service issue when processing location:

![image](https://cloud.githubusercontent.com/assets/11429203/13990835/3211ead0-f0ec-11e5-8108-50002dba6a4c.png)

**Comment by TU-MinW** [comment]
I tried using localhost, didn't encounter IO Error.

**Comment by andywu123** [comment]
please feel free to test it, thanks

**Comment by GraceAi** [comment]
This io error is gone. But AddBoring service returns null(should return true or return errors):
![image](https://cloud.githubusercontent.com/assets/11429203/13997901/a87f4424-f10a-11e5-86ae-95e259c3688e.png)

**Comment by GraceAi** [comment]
tested and confirmed ok
