### ISSUE TITLE
Borings tab - import boring service error

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#29]
Encountered a service error with this service: http://apps.ecointegration.com/GeoTracker%20Services/api/BoringIssues/AddBoringIssues?

![image](https://cloud.githubusercontent.com/assets/11429203/13991014/cdd7c6c4-f0ec-11e5-81ed-2334420e4f70.png)

**Comment by andywu123** [comment]
Hi Grace, do you mind to try again see if it works as the services is just updated?
If it's still not working, I may like to proceed further debug on server

**Comment by GraceAi** [comment]
Hi Andy, I cleared the cache and tried again but still encountered this issue. Min, can you confirm?

**Comment by andywu123** [comment]
Thank you, I will debug on the server later.

**Comment by andywu123** [comment]
Please feel free to test again

**Comment by GraceAi** [comment]
Tested and Confirmed OK
