### ISSUE TITLE
ExportGPJ issue - point table 

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#44]
Is_relocated and Auger_Refusal columns have wrong values populated.
![image](https://user-images.githubusercontent.com/11429203/33677163-dc69127c-da85-11e7-8886-e28841e9f6fa.png)

![image](https://user-images.githubusercontent.com/11429203/33677208-fd106994-da85-11e7-8ca2-07b701dfdfa9.png)

**Comment by andywu123** [comment]
fixed, please update code
