### ISSUE TITLE
Requests tab - create request error

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#5]
If user only fills out Primary Contact Office and Secondary Contact Office, the following error is encountered:

![image](https://cloud.githubusercontent.com/assets/11429203/13852420/5471e048-ec38-11e5-8a2e-f6f8d5e034f9.png)

**Comment by TU-MinW** [comment]
Have to fill all the text input values when create request. I will add input validation after all testing done.

**Comment by andywu123** [comment]
pc phone is  supposed to be required
