### ISSUE TITLE
Requests tab - multiple Add new Boring windows displayed

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#7]
After cancel add a new boring and click "Add" button again to add a new boring, multiple Add New Boring windows would be displayed:
![image](https://cloud.githubusercontent.com/assets/11429203/13855807/7647f616-ec48-11e5-98f4-f0ebd28d5ddf.png)

**Comment by TU-MinW** [comment]
Fixed. Please try again.

**Comment by GraceAi** [comment]
Tested and confirmed OK
