### ISSUE TITLE
Requests tab - Add New Boring zoom to map point

### ISSUE THREAD

**Issue by GraceAi** [andywu123/Geotracker#9]
Is it possible to zoom in to the point after use fill in X, Y coordinates?
Also, seems like user can't see the point change if they change the values of X and Y.
![image](https://cloud.githubusercontent.com/assets/11429203/13856212/7c102012-ec4a-11e5-8b87-0d9010db269a.png)

**Comment by TU-MinW** [comment]
Map point is updated. And John says we don't need to zoom map when adding borings.

**Comment by GraceAi** [comment]
Tested and confirmed OK
